### ISSUE TITLE
boardview.create_view endpoint is missing entirely

### ISSUE THREAD

**Issue by fake-name** [akprasad/flask-forum#5]
The index page refers to the `boardview.create_view` endpoint (`url_for('boardview.create_view')`), which does not seem to exist in the codebase at all.

**Comment by akprasad** [comment]
Sorry for the 7 years late follow-up! This was a hobby project that I didn't expect to ever become used by others. Agreed that the rough edge is obnoxious. I'll add a disclaimer to the project.
