### ISSUE TITLE
Dependency on `lessc` entirely undocumented.

### ISSUE THREAD

**Issue by fake-name** [akprasad/flask-forum#6]
Apparently the forum automatically uses less to build CSS files? In any event, if you don't have `less` and `lessc` installed, it won't bootstrap.

That should probably be documented somewhere.

**Comment by fake-name** [comment]
As a sidenote, having a dependency on node is rather obnoxious.

**Comment by akprasad** [comment]
Sorry for the 7 years late follow-up! This was a hobby project that I didn't expect to ever become used by others. Agreed that the rough edge is obnoxious. I'll add a disclaimer to the project.
